name: Update Regulatory News Feed

on:
  schedule:
    # Runs every day at 07:00 and 13:00 UTC
    - cron: '0 7 * * *'
    - cron: '0 13 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install xml2js

      - name: Fetch RSS feeds and generate markdown
        run: node fetch-feeds.js

      - name: Commit updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/regulatory-news.md
          git diff --cached --quiet || git commit -m "🔄 Update regulatory news feed - $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
